<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8U2QFS4" failures="0" tests="5" name="Test.TestCase" time="0.096" errors="1" timestamp="2023-01-19T01:59:54 IST" skipped="4">
  <testcase classname="Test.TestCase" name="VFTC4" time="0.096">
    <error message="bound must be positive" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: bound must be positive
at java.base/java.util.Random.nextInt(Random.java:321)
at Core.SeleniumFunctions.anyItem(SeleniumFunctions.java:156)
at Page.VFhomepage.randomDropdownValGenerator(VFhomepage.java:74)
at Page.VFhomepage.verifyfilterFunctionality(VFhomepage.java:47)
at Test.TestCase.VFTC4(TestCase.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VFTC4 -->
  <system-out/>
  <testcase classname="Test.TestCase" name="VFTC3">
    <skipped/>
  </testcase> <!-- VFTC3 -->
  <system-out/>
  <testcase classname="Test.TestCase" name="VFTC2">
    <skipped/>
  </testcase> <!-- VFTC2 -->
  <system-out/>
  <testcase classname="Test.TestCase" name="VFTC1">
    <skipped/>
  </testcase> <!-- VFTC1 -->
  <system-out/>
  <testcase classname="Test.TestCase" name="VFTC5">
    <skipped/>
  </testcase> <!-- VFTC5 -->
  <system-out/>
</testsuite> <!-- Test.TestCase -->
